stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw/credit_scoring.csv
    outs:
      - data/processed/train.csv
      - data/processed/val.csv
      - data/processed/test.csv
      - models/scaler.joblib

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/train.csv
      - data/processed/val.csv
    outs:
      - models/model_baseline.joblib

  tune:
    cmd: python src/tune.py
    deps:
      - src/tune.py
      - data/processed/train.csv
      - data/processed/val.csv
    outs:
      - models/best_model.joblib
